# Numpy

In [13]:
#Import Numpy Library

import numpy as np
from numpy import random

In [15]:
#create simple arrary from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr.ndim # dimention

2

In [17]:
arr.shape # shape of array

(2, 4)

In [18]:
type (arr)

numpy.ndarray

In [19]:
arr.data #memory location

# Random Number Generator using numpy

In [20]:
x= random.randint(100)
x

55

In [21]:
x= random.rand()
x

0.6443307335576427

In [22]:
x= random.rand(5)
x

array([0.34084814, 0.95873876, 0.74049138, 0.187986  , 0.21146581])

In [23]:
x= random.randint(100, size=(5))
x

array([63, 85, 64, 66, 98])

In [24]:
x= random.randint(100, size=(5,3))
x

array([[36,  8, 76],
       [94, 42, 90],
       [94, 98, 53],
       [78, 21, 15],
       [78, 78, 81]])

In [25]:
#a=1D array ,with 7 integer
#b=1D array ,with 7 integer
#math operation.

a= random.randint(100, size=(7))
print(a)
b= random.randint(100, size=(7))
print(b)

z= a+b
print(z)



[ 6 84 47 79 98  6 55]
[44 65 36 33 35 79 59]
[ 50 149  83 112 133  85 114]


In [26]:
a

array([ 6, 84, 47, 79, 98,  6, 55])

In [27]:
b

array([44, 65, 36, 33, 35, 79, 59])

In [28]:
z=a+b
z

array([ 50, 149,  83, 112, 133,  85, 114])

# matrix in numpy

In [29]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [30]:
b=np.matrix('1 2 3; 4 5 6; 7 8 9')
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
c= np.matrix([[5, 6, 7], [4, 6, 6,]])
c

matrix([[5, 6, 7],
        [4, 6, 6]])

# Measure of Central Tendency

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.amin(arr)

1

In [34]:
np.amax(arr)

9

In [35]:
np.mean(arr)

5.0

In [36]:
np.median(arr)

5.0

In [37]:
np.std(arr) #std. deviation

2.581988897471611

In [38]:
np.var(arr)
                                        

6.666666666666667